### ISSUE TITLE
bug：双指滚动浏览器界面时，经常会出现卡住的情况。

### ISSUE THREAD

**Issue by alphajx** [songhao/BetterAndBetter#10]
双指滚动浏览器界面时，经常会出现卡住的情况。

配置：
![image](https://user-images.githubusercontent.com/36352860/51363607-c3834780-1b13-11e9-9a01-375f55b086a4.png)

**Comment by suliveevil** [comment]
在 release 页面下载最新版，如有问题再开 issue。

**Comment by southwolf** [comment]
1.6.78 仍然存在同样问题 @suliveevil  @songhao
