### ISSUE TITLE
开启后，进入Intellij IDEA会无法打字

### ISSUE THREAD

**Issue by gimyum20** [songhao/BetterAndBetter#2]
只开启鼠标手势。正常使用，一般半小时，进去 ide 编辑器，会卡死。无法打字，无法操作。关闭后能正常打字，再启动后正常。之后也会偶然出现。

另外，偶然情况下，会无故退出。

mac: 10.13.6  15寸2018款touch bar 512G

**Comment by songhao** [comment]
进群聊吧，谢谢
