### ISSUE TITLE
请求作者开源

### ISSUE THREAD

**Issue by luo-chuan** [songhao/BetterAndBetter#3]
作者大概是把GitHub当作网盘来用了。作者上传的不是源代码，而是编译好的软件包。编译好的软件包应发布在releases里。这个软件挺好的，真心希望开源。

**Comment by suliveevil** [comment]
不是所有好软件都应该开源的。付费比捐赠能更好的支持开发者。

**Comment by suliveevil** [comment]
Alex 不太会用 GitHub，现在这个 repo 由我参与管理。
