### ISSUE TITLE
软件造成系统卡顿&剪切板问题

### ISSUE THREAD

**Issue by hjmmc** [songhao/BetterAndBetter#7]
症状：
1.打开启动台动画明显卡顿
2.鼠标滚动页面明显卡顿
关闭BAB后症状消失
之后出现了com.apple.hiservices-xpcservice 没有响应
<img width="364" alt="5863f6dc-5d8b-4a7c-a612-a6de89b58983" src="https://user-images.githubusercontent.com/12729036/48611897-4c6ded80-e9c2-11e8-8341-19a1193f641a.png">
百度得出可能是鼠标驱动问题 [这里](https://bbs.feng.com/read-htm-tid-11861813-page-2.html)
<img width="835" alt="qq20181116-171031 2x" src="https://user-images.githubusercontent.com/12729036/48611986-948d1000-e9c2-11e8-9146-c40a59460b6d.png">

我的配置：
已开启平滑鼠标滚轮（很可能是这里的Bug）
映射鼠标3，4键为前进后退

除了卡顿以外还有个小问题
偶尔出现粘贴板内容被选中内容覆盖的情况。。。
比如我复制了 ‘aaa’ 想要替换 ‘bbb’
当我选中 ‘bbb’ 然后按下 ctrl+v 发现 ‘bbb’ 并没有替换为  ‘aaa’
在空白处粘贴竟然内容变成了  ‘bbb’ 。。。但我并没有开启剪切板管理的功能。。。

**Comment by kylin17** [comment]
没有外接鼠标直接用触摸板也会出现``com.apple.hiservices-xpcservice`` 没有响应。
