### ISSUE TITLE
bug: visual studio code + better，鼠标选择任何字符，总是自动拷贝到内存，导致粘贴板使用异常

### ISSUE THREAD

**Issue by membphis** [songhao/BetterAndBetter#8]

**Comment by membphis** [comment]
如果退出 better 软件，则正常。

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/49450074-36ac5500-f817-11e8-81a8-fee13a298617.png)

disable this feature, works fine now.

**Comment by JimLee1996** [comment]
遇到同样的问题。除了Vscode外，包括微软的其他软件，word、ppt/excel等

**Comment by suliveevil** [comment]
黑名单，解决不了的就拉黑。
